### ISSUE TITLE
Accept pictures in CFP.

### ISSUE THREAD

**Issue by HarshKapadia2** [OurTechCommunity/talks#9]
To create a poster for each OTC Talks session, we need the picture(s) of the speaker(s), but we aren't currently taking any pictures in our CFP, so we will have to ask the speaker(s) for it, which creates a delay and additional effort.

To avoid this, I think we should add a **compulsory** input in the CFP Google Form to accept URLs. (I hope no one Rick Rolls us haha. Can we restrict the URLs to images in Google Forms? I don't think so.)

In Google Forms, I think a Short Answer with URL Text validation would be better than a File Upload input, as the File Upload input stores files on our Google Drive, which will unnecessarily use up our storage. The advantage with a File Upload Input though is that we can restrict file sizes (Eg: '10 MB') and types (Eg: 'Images').

**Comment by tusharnankani** [comment]
> In Google Forms, I think a Short Answer with URL Text validation would be better than a File Upload input, as the File Upload input stores files on our Google Drive, which will unnecessarily use up our storage. The advantage with a File Upload Input though is that we can restrict file sizes (Eg: '10 MB') and types (Eg: 'Images').

Wow, that's a good idea.

> I hope no one Rick Rolls us haha.

That's not a problem.

> Can we restrict the URLs to images in Google Forms? 

I don't think so.

**Comment by tusharnankani** [comment]
![image](https://user-images.githubusercontent.com/61280281/211618338-873041c1-c195-457d-9b73-9c08d93f6330.png)

[Done](https://docs.google.com/forms/d/e/1FAIpQLSfEBH3telvAPDbtMFBpyeTgIZqsA2J5Bc3cwDgIO5kvdtT7fQ/viewform).

**Comment by HarshKapadia2** [comment]
Thank you, Tushar!
